# Generated by Django 5.0.6 on 2024-08-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_modified_date_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
